name: WDP-Start
version: ${project.version}
main: com.wdp.start.WDPStartPlugin
api-version: '1.21'
description: Professional Get Started Quest System for New Player Onboarding
author: WDP Development Team
website: https://wdpserver.com

softdepend:
  - Vault
  - AuraSkills
  - WDP-Progress
  - WDP-BaseDet
  - WorldGuard
  - DiscordSRV

commands:
  quests:
    description: Open the quest menu or manage quests
    usage: /<command> [start|cancel|help|reload]
    aliases: [quest, getstarted, wdpstart, start]

permissions:
  wdpstart.use:
    description: Allows access to the quest system
    default: true
  wdpstart.menu:
    description: Allows opening the quest menu
    default: true
  wdpstart.cancel:
    description: Allows cancelling the quest chain
    default: true
  wdpstart.admin:
    description: Admin permissions for WDP-Start
    default: op
  wdpstart.admin.reload:
    description: Allows reloading the plugin
    default: op
  wdpstart.admin.reset:
    description: Allows resetting player progress
    default: op
  wdpstart.admin.complete:
    description: Allows force-completing quests
    default: op
  wdpstart.admin.debug:
    description: Allows viewing debug information
    default: op
